import type { Glide, Mouse, Mousepad } from "@/lib/types";

const baseMice: Mouse[] = [
  {
    slug: "logitech-gpro-x2",
    brand: "Logitech",
    name: "G Pro X Superlight 2",
    sensor: "HERO 2",
    dpiMax: 44000,
    weightG: 60,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "LIGHTFORCE optical",
    clickLatencyMs: 0.9,
    handSize: "medium",
    priceUsd: 159,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale", "moba"],
  },
  {
    slug: "razer-viper-v3-pro",
    brand: "Razer",
    name: "Viper V3 Pro",
    sensor: "Focus Pro 35K Gen-2",
    dpiMax: 35000,
    weightG: 54,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical Gen-3",
    clickLatencyMs: 0.6,
    handSize: "universal",
    priceUsd: 179,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "lamzu-atlantis-mini",
    brand: "Lamzu",
    name: "Atlantis Mini",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 49,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: true,
    switches: "Kailh GM 8.0",
    clickLatencyMs: 1.1,
    handSize: "small",
    priceUsd: 99,
    profiles: ["tactical-fps", "hero-shooter", "moba"],
  },
  {
    slug: "vxe-r1-se-plus",
    brand: "VXE",
    name: "R1 SE Plus",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 55,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "Huano Pink Dot",
    clickLatencyMs: 1.4,
    handSize: "medium",
    priceUsd: 45,
    profiles: ["moba", "mmo", "battle-royale"],
  },
  {
    slug: "pulsar-x2h-mini",
    brand: "Pulsar",
    name: "X2H Mini",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 52,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 1000,
    motionSync: true,
    switches: "Pulsar Optical",
    clickLatencyMs: 1.2,
    handSize: "small",
    priceUsd: 119,
    profiles: ["tactical-fps", "hero-shooter"],
  },
  {
    slug: "zowie-ec2-cw",
    brand: "Zowie",
    name: "EC2-CW",
    sensor: "PAW3370",
    dpiMax: 3200,
    weightG: 77,
    shape: "ergonomic",
    grips: ["palm"],
    connectivity: "wireless",
    pollingHz: 1000,
    motionSync: false,
    switches: "Huano mechanical",
    clickLatencyMs: 2.0,
    handSize: "large",
    priceUsd: 149,
    profiles: ["tactical-fps", "mmo", "moba"],
  },
  {
    slug: "endgamegear-xm2we",
    brand: "Endgame Gear",
    name: "XM2we",
    sensor: "PixArt PAW3370",
    dpiMax: 19000,
    weightG: 63,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 1000,
    motionSync: true,
    switches: "Kailh GO Optical",
    clickLatencyMs: 1.3,
    handSize: "large",
    priceUsd: 109,
    profiles: ["battle-royale", "mmo", "moba"],
  },
  {
    slug: "attack-shark-x11",
    brand: "Attack Shark",
    name: "X11",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 49,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "Kailh GM 8.0",
    clickLatencyMs: 1.5,
    handSize: "small",
    priceUsd: 40,
    profiles: ["moba", "hero-shooter"],
  },
  {
    slug: "ninjutso-sora-v2",
    brand: "Ninjutso",
    name: "Sora V2",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 42,
    shape: "ergonomic",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical 60M",
    clickLatencyMs: 0.8,
    handSize: "small",
    priceUsd: 129,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "wlmouse-ymax",
    brand: "WLMouse",
    name: "YMAX",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 38,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.7,
    handSize: "universal",
    priceUsd: 189,
    profiles: ["tactical-fps", "hero-shooter"],
  },
];

const basePads: Mousepad[] = [
  {
    slug: "artisan-zero-xl",
    brand: "Artisan",
    name: "Zero (XSoft) XL",
    surface: "control",
    thicknessMm: 4,
    dynamicFrictionX: 25,
    dynamicFrictionY: 25.3,
    staticFrictionX: 27,
    staticFrictionY: 27.3,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Zero Black XSoft",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 45,
  },
  {
    slug: "artisan-hien-mid",
    brand: "Artisan",
    name: "Hien (Mid)",
    surface: "speed",
    thicknessMm: 3,
    dynamicFrictionX: 17.5,
    dynamicFrictionY: 19,
    staticFrictionX: 19,
    staticFrictionY: 21,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA-proxy",
    frictionProxyOf: "Artisan Hien XSoft (cisA: 19.50/22.50)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 48,
  },
  {
    slug: "xraypad-aqua-control-plus",
    brand: "X-raypad",
    name: "Aqua Control Plus",
    surface: "hybrid",
    thicknessMm: 4,
    dynamicFrictionX: 22,
    dynamicFrictionY: 23,
    staticFrictionX: 24,
    staticFrictionY: 25,
    surfaceTexture: "textured",
    thickness: 4,
    frictionSource: "cisA-proxy",
    frictionProxyOf: "X-Raypad AquaControll 2 (cisA: 21.00/21.00)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 35,
  },
  {
    slug: "skypad-glass-3",
    brand: "SkyPAD",
    name: "Glass 3.0 XL",
    surface: "glass",
    thicknessMm: 4,
    dynamicFrictionX: 17,
    dynamicFrictionY: 17,
    staticFrictionX: 19,
    staticFrictionY: 19,
    surfaceTexture: "glass",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Skypad 3.0",
    stitchedEdges: false,
    base: "silicone grip",
    priceUsd: 89,
  },
  {
    slug: "esptiger-kin-2",
    brand: "EspTiger",
    name: "Kin 2",
    surface: "hybrid",
    thicknessMm: 3,
    dynamicFrictionX: 20,
    dynamicFrictionY: 22,
    staticFrictionX: 22,
    staticFrictionY: 24,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA-proxy",
    frictionProxyOf: "ESP Tiger Ling Yun (cisA: 23.50/22.80)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 22,
  },
  {
    slug: "qck-heavy",
    brand: "SteelSeries",
    name: "QcK Heavy",
    surface: "control",
    thicknessMm: 6,
    dynamicFrictionX: 22,
    dynamicFrictionY: 23,
    staticFrictionX: 26,
    staticFrictionY: 27,
    surfaceTexture: "smooth",
    thickness: 6,
    frictionSource: "cisA-proxy",
    frictionProxyOf: "SteelSeries QCK+ Limited (cisA: 22.00/23.00)",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 20,
  },
];

/**
 * Глайды по сегментам рынка СНГ.
 *
 * Индексы speed и durability — сравнительные оценки на основе материала,
 * толщины и позиционирования бренда, а не лабораторные измерения.
 * Цены ориентировочные и пересчитаны из рублёвых, поэтому зависят от курса.
 */
const extraGlides: Glide[] = [
  /* ---------- Бюджетный сегмент ---------- */
  {
    slug: "proaim-almaz",
    brand: "ProAim",
    name: "Almaz",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 55,
    durabilityIndex: 55,
    priceUsd: 5,
    tier: "budget",
    form: "dots",
    packContents: "большой набор универсальных точек",
    note: "Самый доступный киберспортивный бренд СНГ. Подходит для первых экспериментов с материалами.",
    specSource: "estimated",
  },
  {
    slug: "proaim-graphite",
    brand: "ProAim",
    name: "Graphite",
    material: "ptfe-mos2",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 62,
    durabilityIndex: 68,
    priceUsd: 6,
    tier: "budget",
    form: "dots",
    packContents: "большой набор универсальных точек",
    note: "PTFE с добавкой: дешёвый способ попробовать более скользкий вариант.",
    specSource: "estimated",
  },
  {
    slug: "proaim-kvartz",
    brand: "ProAim",
    name: "Kvartz",
    material: "uhmw-pe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 58,
    durabilityIndex: 72,
    priceUsd: 6,
    tier: "budget",
    form: "dots",
    packContents: "большой набор универсальных точек",
    note: "UHMW-PE держит абразив лучше чистого PTFE при схожей цене.",
    specSource: "estimated",
  },
  {
    slug: "oem-ptfe-dots",
    brand: "OEM",
    name: "Универсальные PTFE-точки",
    material: "ptfe",
    thicknessMm: 0.7,
    diameterMm: 100,
    speedIndex: 48,
    durabilityIndex: 40,
    priceUsd: 3,
    tier: "budget",
    form: "dots",
    packContents: "безбрендовый набор точек",
    note: "Простые белые точки с китайских фабрик. Годятся для проверки формы, но ресурс невелик.",
    specSource: "estimated",
  },

  /* ---------- Средний сегмент ---------- */
  {
    slug: "nova-union-tma-v2",
    brand: "Nova Union",
    name: "Тьма V2",
    material: "uhmw-pe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 66,
    durabilityIndex: 82,
    priceUsd: 14,
    tier: "mid",
    form: "dots",
    note: "UHMW-PE вместо PTFE: заметно выше стойкость к истиранию, характер скольжения плотнее.",
    specSource: "estimated",
  },
  {
    slug: "nova-union-iskra",
    brand: "Nova Union",
    name: "Искра",
    material: "ptfe-mos2",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 74,
    durabilityIndex: 72,
    priceUsd: 14,
    tier: "mid",
    form: "dots",
    note: "Быстрый вариант линейки под тканевые коврики среднего трения.",
    specSource: "estimated",
  },
  {
    slug: "nova-union-volna",
    brand: "Nova Union",
    name: "Волна",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 60,
    durabilityIndex: 65,
    priceUsd: 13,
    tier: "mid",
    form: "dots",
    note: "Сбалансированный PTFE: компромисс между контролем и скоростью.",
    specSource: "estimated",
  },
  {
    slug: "nova-union-mgla",
    brand: "Nova Union",
    name: "Мгла",
    material: "ptfe",
    thicknessMm: 0.9,
    diameterMm: 100,
    speedIndex: 53,
    durabilityIndex: 70,
    priceUsd: 13,
    tier: "mid",
    form: "dots",
    note: "Более медленный вариант под быстрые коврики, где нужен запас контроля.",
    specSource: "estimated",
  },
  {
    slug: "xraypad-obsidian",
    brand: "X-raypad",
    name: "Obsidian",
    material: "ptfe",
    thicknessMm: 0.85,
    diameterMm: 100,
    speedIndex: 64,
    durabilityIndex: 78,
    priceUsd: 12,
    tier: "mid",
    form: "dots",
    note: "Текстурированная поверхность: скольжение мягче, чем у гладкого PTFE.",
    specSource: "estimated",
  },
  {
    slug: "xraypad-obsidian-air",
    brand: "X-raypad",
    name: "Obsidian Air",
    material: "ptfe",
    thicknessMm: 0.7,
    diameterMm: 100,
    speedIndex: 72,
    durabilityIndex: 72,
    priceUsd: 12,
    tier: "mid",
    form: "dots",
    note: "Облегчённая версия Obsidian: тоньше и быстрее.",
    specSource: "estimated",
  },
  {
    slug: "corepad-ctrl",
    brand: "Corepad",
    name: "Skatez CTRL",
    material: "ptfe",
    thicknessMm: 0.9,
    diameterMm: 100,
    speedIndex: 45,
    durabilityIndex: 82,
    priceUsd: 10,
    tier: "mid",
    form: "full-size",
    packContents: "два набора в упаковке",
    note: "Контрольный профиль: намеренно медленнее обычного PTFE.",
    specSource: "estimated",
  },

  /* ---------- Премиальный сегмент ---------- */
  {
    slug: "esptiger-ice-v2",
    brand: "ESPTIGER",
    name: "ICE v2",
    material: "ptfe",
    thicknessMm: 0.75,
    diameterMm: 100,
    speedIndex: 76,
    durabilityIndex: 84,
    priceUsd: 18,
    tier: "premium",
    form: "anatomic",
    note: "Анатомическая форма под конкретные модели мышей, аккуратный клеевой слой.",
    specSource: "estimated",
  },
  {
    slug: "esptiger-arc-1",
    brand: "ESPTIGER",
    name: "Arc 1",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 70,
    durabilityIndex: 82,
    priceUsd: 17,
    tier: "premium",
    form: "anatomic",
    note: "Скруглённые кромки: плавный вход в движение.",
    specSource: "estimated",
  },
  {
    slug: "esptiger-ctrl",
    brand: "ESPTIGER",
    name: "CTRL",
    material: "ptfe",
    thicknessMm: 0.9,
    diameterMm: 100,
    speedIndex: 48,
    durabilityIndex: 86,
    priceUsd: 17,
    tier: "premium",
    form: "anatomic",
    note: "Премиальный контрольный профиль для быстрых поверхностей.",
    specSource: "estimated",
  },
  {
    slug: "nova-union-lotos",
    brand: "Nova Union",
    name: "Лотос",
    material: "glass",
    thicknessMm: 0.6,
    diameterMm: 100,
    speedIndex: 94,
    durabilityIndex: 95,
    priceUsd: 30,
    tier: "premium",
    form: "dots",
    note: "Закалённое алюмосиликатное стекло: очень низкое трение и большой ресурс. На стеклянном коврике сочетание нежелательно.",
    specSource: "estimated",
  },
  {
    slug: "nova-union-photon",
    brand: "Nova Union",
    name: "Фотон",
    material: "glass",
    thicknessMm: 0.6,
    diameterMm: 100,
    speedIndex: 96,
    durabilityIndex: 95,
    priceUsd: 32,
    tier: "premium",
    form: "dots",
    note: "Самый быстрый вариант линейки. Требует привычки: контроль минимальный.",
    specSource: "estimated",
  },
  {
    slug: "pulsar-superglide-2",
    brand: "Pulsar",
    name: "Superglide 2",
    material: "glass",
    thicknessMm: 0.6,
    diameterMm: 100,
    speedIndex: 95,
    durabilityIndex: 94,
    priceUsd: 33,
    tier: "premium",
    form: "anatomic",
    note: "Стеклянные глайды под конкретные модели мышей.",
    specSource: "estimated",
  },
  {
    slug: "xraypad-jade-air-dots",
    brand: "X-raypad",
    name: "Jade Air Dots",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 6.5,
    speedIndex: 75,
    durabilityIndex: 75,
    priceUsd: 10,
    tier: "budget",
    form: "dots",
    packContents: "40 точек 6,5 мм + салфетки для очистки",
    note: "Чистый PTFE с демпфирующим слоем: тише стандартного Jade. По шкале производителя быстрее Obsidian. Толщина 0,8 мм требует подтверждения.",
    specSource: "estimated",
  },
  {
    slug: "hyperglide",
    brand: "Hyperglide",
    name: "Hyperglide",
    material: "ptfe",
    thicknessMm: 0.81,
    diameterMm: 100,
    speedIndex: 72,
    durabilityIndex: 72,
    priceUsd: 10,
    tier: "mid",
    note: "Классические кат-глайды 0,81 мм — эталон бюджетного апгрейда скольжения. Требует разнашивания.",
    specSource: "estimated",
  },
  {
    slug: "corepad-skatez-pro",
    brand: "Corepad",
    name: "Skatez PRO",
    material: "ptfe",
    thicknessMm: 0.85,
    diameterMm: 100,
    speedIndex: 70,
    durabilityIndex: 78,
    priceUsd: 8,
    tier: "budget",
    note: "Чистый PTFE 0,8 мм, вырез под конкретные модели мышей. Ресурс выше среднего.",
    specSource: "estimated",
  },
  {
    slug: "xraypad-jade-pro",
    brand: "X-raypad",
    name: "Jade Pro",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 80,
    durabilityIndex: 80,
    priceUsd: 12,
    tier: "mid",
    note: "Чистый PTFE 0,8 мм: быстрее обычного Jade, заметно громче Jade Air.",
    specSource: "estimated",
  },
  {
    slug: "xraypad-jade-air",
    brand: "X-raypad",
    name: "Jade Air",
    material: "ptfe",
    thicknessMm: 0.6,
    diameterMm: 100,
    speedIndex: 78,
    durabilityIndex: 72,
    priceUsd: 11,
    tier: "budget",
    note: "Тонкий чистый PTFE ~0,6 мм: скорость Jade, но тише и дешевле. Толщина требует подтверждения.",
    specSource: "estimated",
  },
  {
    slug: "xraypad-u9-dots",
    brand: "X-raypad",
    name: "U9 Control Dots",
    material: "uhmw-pe",
    thicknessMm: 0.8,
    diameterMm: 6.5,
    speedIndex: 45,
    durabilityIndex: 98,
    priceUsd: 15,
    tier: "premium",
    form: "dots",
    packContents: "универсальные точки",
    note: "Максимальный контроль и заявленный ресурс в 6–9 раз выше стандартных PTFE-глайдов.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "X-raypad — официальный гайд",
        url: "https://shop.x-raypad.com/best-mouse-skates-for-fps-jade-vs-obsidian-vs-u9-guide",
      },
    ],
  },
  {
    slug: "xraypad-obsidian-pro-air-upe",
    brand: "X-raypad",
    name: "Obsidian Pro Air U-PE Dots",
    material: "uhmw-pe",
    thicknessMm: 0.8,
    diameterMm: 6.5,
    speedIndex: 50,
    durabilityIndex: 96,
    priceUsd: 16,
    tier: "premium",
    form: "dots",
    note: "Тихие износостойкие U-PE точки с акцентом на контроль.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "X-raypad — официальный каталог",
        url: "https://shop.x-raypad.com/",
      },
    ],
  },
  {
    slug: "xraypad-meteorite-dots",
    brand: "X-raypad",
    name: "Meteorite Glass Dots",
    material: "glass",
    thicknessMm: 0.8,
    diameterMm: 6.5,
    speedIndex: 98,
    durabilityIndex: 99,
    priceUsd: 20,
    tier: "premium",
    form: "dots",
    note: "Точки из закалённого стекла для тканевых ковриков; не использовать на стеклянных ковриках.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "X-raypad — официальный каталог",
        url: "https://shop.x-raypad.com/product-category/products/x-ray-gaming-mouse-pads/mouse-feet",
      },
    ],
  },
  {
    slug: "xraypad-jade-ultra",
    brand: "X-raypad",
    name: "Jade Ultra",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 88,
    durabilityIndex: 84,
    priceUsd: 13,
    tier: "mid",
    form: "anatomic",
    note: "Быстрый PTFE с антиколлапсным наполнением для стабильного скольжения под давлением.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "X-raypad — официальный каталог",
        url: "https://shop.x-raypad.com/product-category/products/x-ray-gaming-mouse-pads/mouse-feet",
      },
    ],
  },
  {
    slug: "xraypad-obsidian-ultra",
    brand: "X-raypad",
    name: "Obsidian Ultra",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 62,
    durabilityIndex: 88,
    priceUsd: 13,
    tier: "mid",
    form: "anatomic",
    note: "Контрольный PTFE с антиколлапсной конструкцией.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "X-raypad — официальный каталог",
        url: "https://shop.x-raypad.com/product-category/products/x-ray-gaming-mouse-pads/mouse-feet",
      },
    ],
  },
  {
    slug: "wallhack-ptfe-black-dots",
    brand: "Wallhack",
    name: "PTFE Black Dots",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 7,
    speedIndex: 90,
    durabilityIndex: 72,
    priceUsd: 20,
    tier: "premium",
    form: "dots",
    packContents: "40 точек",
    note: "Универсальные быстрые PTFE-точки со скруглённой кромкой.",
    specSource: "official",
    releaseYear: 2025,
    sources: [
      {
        label: "Wallhack — официальный сайт",
        url: "https://wallhack.com/en-int/products/wallhack-skates-ptfe-black-dots",
      },
    ],
  },
  {
    slug: "wallhack-ptfe-black-silent",
    brand: "Wallhack",
    name: "PTFE Black Dots Silent",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 7,
    speedIndex: 76,
    durabilityIndex: 72,
    priceUsd: 20,
    tier: "premium",
    form: "dots",
    note: "Более тихий вариант с увеличенной площадью контакта и сбалансированной скоростью.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "Wallhack — официальный каталог",
        url: "https://wallhack.com/collections/skates",
      },
    ],
  },
  {
    slug: "wallhack-uhmwpe-black-dots",
    brand: "Wallhack",
    name: "UHMW-PE Black Dots",
    material: "uhmw-pe",
    thicknessMm: 0.8,
    diameterMm: 7,
    speedIndex: 68,
    durabilityIndex: 96,
    priceUsd: 20,
    tier: "premium",
    form: "dots",
    note: "Универсальные износостойкие UHMW-PE-точки с более плотным контролем.",
    specSource: "official",
    releaseYear: 2025,
    sources: [
      {
        label: "Wallhack — официальный каталог",
        url: "https://wallhack.com/collections/skates",
      },
    ],
  },
  {
    slug: "corepad-pro-max",
    brand: "Corepad",
    name: "Skatez PRO MAX",
    material: "ptfe",
    thicknessMm: 0.85,
    diameterMm: 100,
    speedIndex: 82,
    durabilityIndex: 90,
    priceUsd: 15,
    tier: "premium",
    form: "anatomic",
    note: "CNC-фрезерованные глайды из чистого virgin PTFE.",
    specSource: "official",
    releaseYear: 2025,
    sources: [
      {
        label: "Corepad — официальный сайт",
        url: "https://www.corepad.de/en/Corepad-Skatez-Logitech-Teflon-Mousefeet-Mouse-Feet-Hyperglides-Hyperglide/Corepad-CNC-Machined-Milled-Next-Gen-Skatez-PRO-MAX-M318-Logitech-G-PRO-X-Superlight-2-GPX2-GPX-DEX.html",
      },
    ],
  },
  {
    slug: "corepad-hyper-gplus-dots",
    brand: "Corepad",
    name: "HYPER G+ Dots",
    material: "ptfe",
    thicknessMm: 0.8,
    diameterMm: 6.5,
    speedIndex: 84,
    durabilityIndex: 82,
    priceUsd: 10,
    tier: "mid",
    form: "dots",
    note: "Универсальные 6,5-мм PTFE-точки для быстрого скольжения.",
    specSource: "official",
    releaseYear: 2026,
    sources: [
      {
        label: "Corepad — официальный сайт",
        url: "https://www.corepad.de/en/corepad-hyper-dots-g-plus-skatez.html",
      },
    ],
  },
];

export const glides: Glide[] = [
  {
    slug: "corepad-skatez-pro-mos2",
    brand: "Corepad",
    name: "Skatez PRO MoS2",
    material: "ptfe-mos2",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 58,
    durabilityIndex: 85,
    tier: "mid",
    form: "full-size",
    specSource: "estimated",
    priceUsd: 9,
  },
  {
    slug: "tiger-gaming-arc-2",
    brand: "Tiger Gaming",
    name: "Arc 2",
    material: "ptfe-mos2",
    thicknessMm: 0.8,
    diameterMm: 100,
    speedIndex: 70,
    durabilityIndex: 75,
    tier: "budget",
    form: "full-size",
    specSource: "estimated",
    priceUsd: 10,
  },
  {
    slug: "xraypad-jade-thick",
    brand: "X-raypad",
    name: "Jade Thick",
    material: "ptfe",
    thicknessMm: 1.5,
    diameterMm: 100,
    speedIndex: 50,
    durabilityIndex: 80,
    tier: "budget",
    form: "dots",
    specSource: "estimated",
    priceUsd: 8,
  },
  ...extraGlides,
];

const extraMice: Mouse[] = [
  {
    slug: "mchose-a5-v2",
    brand: "MCHOSE",
    name: "A5 V2 Ultra",
    sensor: "PixArt PAW3395",
    dpiMax: 26000,
    weightG: 56,
    shape: "symmetric",
    grips: ["claw", "palm"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: true,
    switches: "Omron Mechanical (60 РјР»РЅ)",
    clickLatencyMs: 1.2,
    handSize: "medium",
    priceUsd: 42,
    profiles: ["hero-shooter", "battle-royale", "moba"],
    dimensionsMm: "121.6 Г— 61.5 Г— 37.7",
    batteryMah: 500,
    batteryLifeH: 130,
    coating: "матовый пластик",
    mcu: "Realtek",
  },
  {
    slug: "mchose-a5-v3",
    brand: "MCHOSE",
    name: "A5 V3 Ultra",
    sensor: "PixArt PAW3395",
    dpiMax: 26000,
    weightG: 56,
    shape: "symmetric",
    grips: ["claw", "palm"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron Mechanical (100 РјР»РЅ)",
    clickLatencyMs: 1.0,
    handSize: "medium",
    priceUsd: 49,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    dimensionsMm: "121.6 Г— 61.5 Г— 37.7",
    batteryMah: 500,
    batteryLifeH: 130,
    coating: "стекловидное Super Glide (улучшенный хват)",
    mcu: "улучшенный Realtek",
  },
  {
    slug: "mchose-ax5-pro-max",
    brand: "MCHOSE",
    name: "AX5 Pro Max",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 54,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Huano Transparent Pink",
    clickLatencyMs: 1.0,
    handSize: "small",
    priceUsd: 59,
    profiles: ["hero-shooter", "battle-royale", "moba"],
    coating: "магниевый экзоскелет, колесо TTC Gold",
  },
  {
    slug: "mchose-ax5-v2",
    brand: "MCHOSE",
    name: "AX5 V2",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 54,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Huano Transparent Pink",
    clickLatencyMs: 0.9,
    handSize: "small",
    priceUsd: 75,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    coating: "магниевый экзоскелет, колесо TTC Gold",
  },
  {
    slug: "mchose-a7-v2-ultra",
    brand: "MCHOSE",
    name: "A7 V2 Ultra",
    sensor: "PAW3950 TI",
    dpiMax: 42000,
    weightG: 59,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.8,
    handSize: "medium",
    priceUsd: 69,
    profiles: ["battle-royale", "hero-shooter", "mmo"],
    batteryMah: 500,
    batteryLifeH: 130,
  },
  {
    slug: "mchose-a7x-ultra",
    brand: "MCHOSE",
    name: "A7X Ultra",
    sensor: "PAW3950 TI",
    dpiMax: 42000,
    weightG: 59,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.8,
    handSize: "medium",
    priceUsd: 79,
    profiles: ["tactical-fps", "battle-royale"],
    batteryMah: 500,
    batteryLifeH: 130,
  },
  {
    slug: "mchose-g3-ultra",
    brand: "MCHOSE",
    name: "G3 Ultra",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 64,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron Mechanical (100 РјР»РЅ)",
    clickLatencyMs: 1.1,
    handSize: "medium",
    priceUsd: 55,
    profiles: ["moba", "mmo", "battle-royale"],
  },
  {
    slug: "mchose-ax5-pro",
    brand: "MCHOSE",
    name: "AX5 Pro",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 52,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: true,
    switches: "Huano Transparent Pink",
    clickLatencyMs: 1.2,
    handSize: "small",
    priceUsd: 46,
    profiles: ["tactical-fps", "hero-shooter", "moba"],
  },
  {
    slug: "mchose-l7-ultra",
    brand: "MCHOSE",
    name: "L7 Ultra",
    sensor: "PixArt PAW3950",
    dpiMax: 30000,
    weightG: 42,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron Optical",
    clickLatencyMs: 0.9,
    handSize: "small",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter"],
    batteryMah: 500,
  },
  {
    slug: "ajazz-aj139-pro-4k",
    brand: "AJAZZ",
    name: "AJ139 Pro 4K",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 51,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: false,
    switches: "Huano Pink Dot",
    clickLatencyMs: 1.4,
    handSize: "small",
    priceUsd: 42,
    profiles: ["hero-shooter", "battle-royale", "moba"],
  },
  {
    slug: "ajazz-aj199-amax",
    brand: "AJAZZ",
    name: "AJ199 Amax",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 55,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: false,
    switches: "Huano Pink Dot",
    clickLatencyMs: 1.5,
    handSize: "medium",
    priceUsd: 38,
    profiles: ["moba", "mmo", "battle-royale"],
  },
  {
    slug: "atk-blazing-sky-x1",
    brand: "ATK",
    name: "Blazing Sky X1 Ultimate",
    sensor: "PAW3950",
    dpiMax: 42000,
    weightG: 51,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.8,
    handSize: "universal",
    priceUsd: 89,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "vxe-mad-r-major",
    brand: "VXE",
    name: "MAD R Major",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 47,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.9,
    handSize: "medium",
    priceUsd: 62,
    profiles: ["tactical-fps", "hero-shooter", "mmo"],
  },
  {
    slug: "kysona-m600",
    brand: "Kysona",
    name: "M600",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 55,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Kailh GM 8.0",
    clickLatencyMs: 1.1,
    handSize: "medium",
    priceUsd: 85,
    profiles: ["battle-royale", "hero-shooter", "mmo"],
  },
  {
    slug: "darmoshark-m3-varun",
    brand: "Darmoshark",
    name: "M3 Varun",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 58,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: false,
    switches: "Kailh GM 4.0",
    clickLatencyMs: 1.3,
    handSize: "medium",
    priceUsd: 45,
    profiles: ["moba", "mmo", "battle-royale"],
  },
  {
    slug: "incott-hpc01m",
    brand: "Incott",
    name: "HPC01M",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 44,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: true,
    switches: "Kailh GM 8.0",
    clickLatencyMs: 1.2,
    handSize: "small",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter"],
  },
  {
    slug: "waizowl-ogm-cloud",
    brand: "Waizowl",
    name: "OGM Cloud",
    sensor: "PAW3395",
    dpiMax: 26000,
    weightG: 49,
    shape: "ergonomic",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 4000,
    motionSync: true,
    switches: "Omron Optical",
    clickLatencyMs: 1.0,
    handSize: "small",
    priceUsd: 75,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "scyrox-v8",
    brand: "Scyrox",
    name: "V8",
    sensor: "PixArt PAW3950",
    dpiMax: 30000,
    weightG: 36,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "TTC optical",
    clickLatencyMs: 0.7,
    handSize: "medium",
    priceUsd: 79,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "wlmouse-beast-x-max",
    brand: "WLMouse",
    name: "Beast X Max",
    sensor: "PixArt PAW3950",
    dpiMax: 30000,
    weightG: 42,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron optical",
    clickLatencyMs: 0.6,
    handSize: "large",
    priceUsd: 159,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    coating: "магниевый сплав",
  },
  {
    slug: "atk-f1-ultimate",
    brand: "ATK",
    name: "F1 Ultimate",
    sensor: "PAW3950 Ultra",
    dpiMax: 42000,
    weightG: 38,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron optical",
    clickLatencyMs: 0.7,
    handSize: "medium",
    priceUsd: 99,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "atk-f1-extreme",
    brand: "ATK",
    name: "F1 Extreme",
    sensor: "PAW3950 Ultra",
    dpiMax: 42000,
    weightG: 35,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron optical",
    clickLatencyMs: 0.7,
    handSize: "medium",
    priceUsd: 119,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "pulsar-x2-v3",
    brand: "Pulsar",
    name: "X2 V3",
    sensor: "PixArt PAW3950",
    dpiMax: 30000,
    weightG: 54,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.8,
    handSize: "medium",
    priceUsd: 119,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "pulsar-xlite-v3-large",
    brand: "Pulsar",
    name: "Xlite V3 Large",
    sensor: "PixArt PAW3395",
    dpiMax: 26000,
    weightG: 58,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 4000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 0.8,
    handSize: "large",
    priceUsd: 99,
    profiles: ["tactical-fps", "battle-royale", "moba"],
  },
  {
    slug: "lamzu-maya-x",
    brand: "Lamzu",
    name: "Maya X",
    sensor: "PixArt PAW3950",
    dpiMax: 30000,
    weightG: 47,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron optical",
    clickLatencyMs: 0.7,
    handSize: "medium",
    priceUsd: 129,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "vxe-mad-r-r1-pro-max",
    brand: "VXE",
    name: "MAD R R1 Pro Max",
    sensor: "PixArt PAW3950",
    dpiMax: 30000,
    weightG: 36,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron optical",
    clickLatencyMs: 0.8,
    handSize: "medium",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "razer-deathadder-v3-pro",
    brand: "Razer",
    name: "DeathAdder V3 Pro",
    sensor: "Focus Pro 30K",
    dpiMax: 30000,
    weightG: 63,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical Gen-3 (90M)",
    clickLatencyMs: 2.0,
    handSize: "large",
    priceUsd: 149,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    batteryLifeH: 90,
  },
  {
    slug: "logitech-g502-x-plus",
    brand: "Logitech",
    name: "G502 X Plus",
    sensor: "HERO 25K",
    dpiMax: 25600,
    weightG: 106,
    shape: "ergonomic",
    grips: ["palm"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "LIGHTFORCE hybrid",
    clickLatencyMs: 2.0,
    handSize: "large",
    priceUsd: 159,
    profiles: ["moba", "mmo", "battle-royale"],
  },
  {
    slug: "zowie-ec2-c",
    brand: "Zowie",
    name: "EC2-C",
    sensor: "PMW3360",
    dpiMax: 3200,
    weightG: 73,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wired",
    pollingHz: 1000,
    motionSync: false,
    switches: "Huano mechanical",
    clickLatencyMs: 2.5,
    handSize: "medium",
    priceUsd: 69,
    profiles: ["tactical-fps", "moba", "mmo"],
    dimensionsMm: "123 × 65 × 42",
  },
  {
    slug: "razer-basilisk-v3-pro",
    brand: "Razer",
    name: "Basilisk V3 Pro",
    sensor: "Focus Pro 30K",
    dpiMax: 30000,
    weightG: 112,
    shape: "ergonomic",
    grips: ["palm"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: true,
    switches: "Optical Gen-3 (90M)",
    clickLatencyMs: 2.0,
    handSize: "large",
    priceUsd: 159,
    profiles: ["tactical-fps", "moba", "mmo", "battle-royale"],
  },
  {
    slug: "logitech-g304",
    brand: "Logitech",
    name: "G304",
    sensor: "HERO",
    dpiMax: 12000,
    weightG: 99,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 1000,
    motionSync: false,
    switches: "Mechanical (10M)",
    clickLatencyMs: 2.5,
    handSize: "medium",
    priceUsd: 39,
    profiles: ["tactical-fps", "hero-shooter", "moba"],
  },
  {
    slug: "attack-shark-x3",
    brand: "Attack Shark",
    name: "X3",
    sensor: "PixArt PAW3395",
    dpiMax: 26000,
    weightG: 49,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "Kailh Black Mamba (80M)",
    clickLatencyMs: 2.5,
    handSize: "medium",
    priceUsd: 40,
    profiles: ["tactical-fps", "hero-shooter"],
  },
  {
    slug: "coolermaster-mm712",
    brand: "Cooler Master",
    name: "MM712",
    sensor: "PixArt PAW3395",
    dpiMax: 19000,
    weightG: 58,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "Optical",
    clickLatencyMs: 2.0,
    handSize: "medium",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "razer-orochi-v2",
    brand: "Razer",
    name: "Orochi V2",
    sensor: "Razer 5G Advanced 18K",
    dpiMax: 18000,
    weightG: 60,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "Mechanical",
    clickLatencyMs: 2.5,
    handSize: "small",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter", "moba"],
    batteryLifeH: 1100,
  },
  {
    slug: "vxe-r1-pro-max",
    brand: "VXE",
    name: "R1 Pro Max",
    sensor: "PixArt PAW3395",
    dpiMax: 26000,
    weightG: 54,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 1000,
    motionSync: false,
    switches: "Huano mechanical",
    clickLatencyMs: 2.5,
    handSize: "medium",
    priceUsd: 46,
    profiles: ["tactical-fps", "hero-shooter"],
  },
  {
    slug: "logitech-g203",
    brand: "Logitech",
    name: "G203 Lightsync",
    sensor: "Mercury",
    dpiMax: 8000,
    weightG: 85,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wired",
    pollingHz: 1000,
    motionSync: false,
    switches: "Mechanical (tension 10M)",
    clickLatencyMs: 3.0,
    handSize: "medium",
    priceUsd: 30,
    profiles: ["tactical-fps", "moba", "mmo"],
  },
  {
    slug: "razer-viper-mini-signature",
    brand: "Razer",
    name: "Viper Mini Signature Edition",
    sensor: "Focus Pro 30K",
    dpiMax: 30000,
    weightG: 49,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical Gen-3",
    clickLatencyMs: 2.0,
    handSize: "medium",
    priceUsd: 279,
    profiles: ["tactical-fps", "hero-shooter"],
  },
  {
    slug: "logitech-g304-x-superlight",
    brand: "Logitech",
    name: "G304 X Superlight",
    sensor: "HERO 44K",
    dpiMax: 44000,
    weightG: 59,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "LIGHTFORCE",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 99,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "razer-deathadder-v4-pro",
    brand: "Razer",
    name: "DeathAdder V4 Pro",
    sensor: "Focus Pro 45K Gen-2",
    dpiMax: 45000,
    weightG: 56,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Razer Optical Gen-4",
    clickLatencyMs: 0.5,
    handSize: "large",
    priceUsd: 179,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "pulsar-x2h-v3-es-mini",
    brand: "Pulsar",
    name: "X2H v3 eS Mini",
    sensor: "Pulsar XS-1",
    dpiMax: 32000,
    weightG: 60,
    shape: "symmetric",
    grips: ["claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Pulsar Optical",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 129,
    profiles: ["tactical-fps", "hero-shooter"],
  },
  {
    slug: "mchose-k7-v2-ultra-plus",
    brand: "MCHOSE",
    name: "K7 V2 Ultra+",
    sensor: "PAW3955 TI",
    dpiMax: 50000,
    weightG: 59,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 79,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "atk-f1-v3-ultimate-plus",
    brand: "ATK",
    name: "Blazing Sky F1 V3 Ultimate+",
    sensor: "PAW3955 Master",
    dpiMax: 50000,
    weightG: 37,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "ATK Custom Optical",
    clickLatencyMs: 0.5,
    handSize: "small",
    priceUsd: 99,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
  },
  {
    slug: "mchose-a7-v3-ultra-plus",
    brand: "MCHOSE",
    name: "A7 V3 Ultra+",
    sensor: "PAW3955 TI",
    dpiMax: 50000,
    weightG: 59,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Omron Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "MCHOSE — официальный сайт",
        url: "https://www.mchose.store/products/mchose-a7-v3-series-lightweight-wireless-gaming-mouse",
      },
    ],
  },
  {
    slug: "attack-shark-x11-ultra",
    brand: "Attack Shark",
    name: "X11 Ultra",
    sensor: "PAW3950MAX",
    dpiMax: 42000,
    weightG: 59,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 89,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    coating: "carbon fiber shell",
    specSource: "official",
    sources: [
      {
        label: "Attack Shark — официальный сайт",
        url: "https://attackshark.com/products/attack-shark-x11ultra",
      },
    ],
  },
  {
    slug: "attack-shark-f1-air",
    brand: "Attack Shark",
    name: "F1 Air",
    sensor: "PAW3955MAX",
    dpiMax: 50000,
    weightG: 39,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 89,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "Attack Shark — анонс производителя",
        url: "https://attackshark.com/blogs/news/f1-air-8k-wireless-gaming-mouse",
      },
    ],
  },
  {
    slug: "attack-shark-r6",
    brand: "Attack Shark",
    name: "R6",
    sensor: "PAW3950MAX",
    dpiMax: 42000,
    weightG: 39,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 79,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "Attack Shark — официальный каталог",
        url: "https://attackshark.com/",
      },
    ],
  },
  {
    slug: "vgn-dragonfly-f1-v5",
    brand: "VGN",
    name: "Dragonfly F1 V5",
    sensor: "PAW3955 Extreme",
    dpiMax: 50000,
    weightG: 53,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 70,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    mcu: "Nordic 54LM20",
    specSource: "official",
    sources: [
      {
        label: "VGN — официальный сайт",
        url: "https://vgnlab.com/collections/mouse",
      },
    ],
  },
  {
    slug: "vgn-dragonfly-king",
    brand: "VGN",
    name: "Dragonfly King",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 54,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical 160M",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 129,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    coating: "magnesium alloy",
    specSource: "official",
    sources: [
      {
        label: "VGN — официальный сайт",
        url: "https://vgnlab.com/collections/mouse",
      },
    ],
  },
  {
    slug: "atk-x1-v2-air-plus",
    brand: "ATK",
    name: "Blazing Sky X1 V2 Air+",
    sensor: "PAW3955 Master",
    dpiMax: 50000,
    weightG: 48,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "ATK Swiftlight",
    clickLatencyMs: 1,
    handSize: "large",
    priceUsd: 99,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-blazing-sky-x1-v2-series-esports-wireless-mouse",
      },
    ],
  },
  {
    slug: "darmoshark-m2-pro",
    brand: "Darmoshark",
    name: "M2 Pro Daero",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 40,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "TTC 60M",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 189,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2025,
    coating: "magnesium alloy",
    specSource: "official",
    sources: [
      {
        label: "Darmoshark — официальный сайт",
        url: "https://darmoshark.com/products/darmoshark-m2-pro-daero-trio-mode-magnesium-alloy-game-mouse",
      },
    ],
  },
  {
    slug: "darmoshark-m3xs-pro",
    brand: "Darmoshark",
    name: "M3XS Pro GhostCat",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 45,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "TTC 60M / Huano 80M",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 99,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2025,
    specSource: "official",
    sources: [
      {
        label: "Darmoshark — официальный сайт",
        url: "https://darmoshark.com/products/darmoshark-m3xs-pro-ghostcat-trio-mode-game-mouse",
      },
    ],
  },
  {
    slug: "ajazz-aj179-apex",
    brand: "AJAZZ",
    name: "AJ179 Apex",
    sensor: "PAW3950",
    dpiMax: 42000,
    weightG: 56,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "100M mechanical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 69,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2025,
    specSource: "official",
    sources: [
      {
        label: "AJAZZ — официальный сайт",
        url: "https://ajazzstore.com/products/ajazz-aj179-series",
      },
    ],
  },
  {
    slug: "mchose-v7",
    brand: "MCHOSE",
    name: "V7",
    sensor: "PAW3955 TI",
    dpiMax: 50000,
    weightG: 54,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 49,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "MCHOSE — официальный сайт",
        url: "https://www.mchose.store/products/mchose-v7-lightweight-ergonomic-wireless-gaming-mouse",
      },
    ],
  },
  {
    slug: "vgn-dragonfly-f2",
    brand: "VGN",
    name: "Dragonfly F2",
    sensor: "PAW3950",
    dpiMax: 42000,
    weightG: 51,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 50,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    mcu: "Nordic 52840 / CX52860",
    specSource: "official",
    sources: [
      {
        label: "VGN — официальный каталог",
        url: "https://vgnlab.com/collections/mouse",
      },
    ],
  },
  {
    slug: "vgn-dragonfly-f2-master",
    brand: "VGN",
    name: "Dragonfly F2 Master",
    sensor: "PAW3950 Extreme",
    dpiMax: 42000,
    weightG: 50,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 60,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "VGN — официальный каталог",
        url: "https://vgnlab.com/collections/mouse",
      },
    ],
  },
  {
    slug: "vgn-dragonfly-y2-v2",
    brand: "VGN",
    name: "Dragonfly Y2 V2",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 49,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "hybrid",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 55,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "VGN — официальный каталог",
        url: "https://vgnlab.com/collections/mouse",
      },
    ],
  },
  {
    slug: "atk-duckbill-ultra",
    brand: "ATK",
    name: "Blazing Sky Duckbill Ultra",
    sensor: "PAW3950 Ultra",
    dpiMax: 42000,
    weightG: 46,
    shape: "symmetric",
    grips: ["palm", "claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "ATK Custom Optical",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 90,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    mcu: "Nordic 54H20",
    coating: "Ice-Feel",
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-blazing-sky-duckbill-wireless-mouse",
      },
    ],
  },
  {
    slug: "atk-z1-v2-ultimate-plus",
    brand: "ATK",
    name: "Blazing Sky Z1 V2 Ultimate+",
    sensor: "PAW3955 Master",
    dpiMax: 50000,
    weightG: 54,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "ATK Custom Optical",
    clickLatencyMs: 1,
    handSize: "large",
    priceUsd: 80,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-blazing-sky-z1-v2-gaming-wireless-mouse",
      },
    ],
  },
  {
    slug: "atk-a9-air-plus",
    brand: "ATK",
    name: "Dragonfly A9 Air+",
    sensor: "PAW3955 Master",
    dpiMax: 42000,
    weightG: 47,
    shape: "symmetric",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "ATK Optical",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 80,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-dragonfly-a9-ultimate-lightweight-wireless-mouse",
      },
    ],
  },
  {
    slug: "atk-a9-mini-plus",
    brand: "ATK",
    name: "Dragonfly A9 Mini+",
    sensor: "PAW3955 Master",
    dpiMax: 42000,
    weightG: 39,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "ATK Optical",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 80,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-dragonfly-a9-ultimate-lightweight-wireless-mouse",
      },
    ],
  },
  {
    slug: "atk-zero",
    brand: "ATK",
    name: "Blazing Sky ZERO",
    sensor: "PAW3950 Ultra",
    dpiMax: 42000,
    weightG: 39,
    shape: "symmetric",
    grips: ["claw", "fingertip"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Optical",
    clickLatencyMs: 1,
    handSize: "small",
    priceUsd: 70,
    profiles: ["tactical-fps", "hero-shooter"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-blazing-sky-zero-ultralight-wireless-gaming-mouse",
      },
    ],
  },
  {
    slug: "atk-dragonfly-y9-ultimate",
    brand: "ATK",
    name: "Dragonfly Y9 Ultimate",
    sensor: "PAW3950",
    dpiMax: 30000,
    weightG: 55,
    shape: "ergonomic",
    grips: ["palm", "claw"],
    connectivity: "wireless",
    pollingHz: 8000,
    motionSync: true,
    switches: "Huano Ice Berry Pink Dot",
    clickLatencyMs: 1,
    handSize: "medium",
    priceUsd: 65,
    profiles: ["tactical-fps", "hero-shooter", "battle-royale"],
    releaseYear: 2026,
    specSource: "official",
    sources: [
      {
        label: "ATK — официальный сайт",
        url: "https://www.atk.store/products/atk-dragonfly-y9-series-lightweight-ergonomic-wireless-mouse",
      },
    ],
  },
];

const extraPads: Mousepad[] = [
  {
    slug: "artisan-zero-daidai-orange-soft",
    brand: "Artisan",
    name: "Zero Daidai Orange Soft",
    surface: "control",
    thicknessMm: 4,
    dynamicFrictionX: 24.5,
    dynamicFrictionY: 24.75,
    staticFrictionX: 26.3,
    staticFrictionY: 26.7,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Zero Daidai Orange Soft",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 55,
  },
  {
    slug: "artisan-type99-xsoft",
    brand: "Artisan",
    name: "Type99 XSoft",
    surface: "control",
    thicknessMm: 4,
    dynamicFrictionX: 26,
    dynamicFrictionY: 21.7,
    staticFrictionX: 27.5,
    staticFrictionY: 24,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Type99 XSoft",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 60,
  },
  {
    slug: "kurosun-ninja-speed",
    brand: "Kurosun",
    name: "Ninja Speed",
    surface: "hybrid",
    thicknessMm: 3.7,
    dynamicFrictionX: 21,
    dynamicFrictionY: 21,
    staticFrictionX: 22,
    staticFrictionY: 22,
    surfaceTexture: "textured",
    thickness: 3.7,
    frictionSource: "cisA",
    frictionProxyOf: "Kurosun Ninja Speed",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 50,
  },
  {
    slug: "artisan-shidenkai-v2-xsoft",
    brand: "Artisan",
    name: "Shidenkai V2 XSoft",
    surface: "glass",
    thicknessMm: 4,
    dynamicFrictionX: 21,
    dynamicFrictionY: 21,
    staticFrictionX: 23,
    staticFrictionY: 23,
    surfaceTexture: "glass",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Shidenkai V2 XSoft",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 75,
  },
  {
    slug: "lgg-jupiter",
    brand: "Lethal Gaming Gear",
    name: "Jupiter",
    surface: "hybrid",
    thicknessMm: 4,
    dynamicFrictionX: 19,
    dynamicFrictionY: 23,
    staticFrictionX: 20,
    staticFrictionY: 25,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Lethal Gaming Gear Jupiter",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 30,
  },
  {
    slug: "xraypad-aqua-control-pro-mid-neon",
    brand: "X-raypad",
    name: "Aqua Control Pro (Mid Neon)",
    surface: "hybrid",
    thicknessMm: 4,
    dynamicFrictionX: 19,
    dynamicFrictionY: 21.5,
    staticFrictionX: 20,
    staticFrictionY: 23,
    surfaceTexture: "textured",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "X-Raypad Aqua Control Pro | Mid Neon",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 30,
  },
  {
    slug: "meowgaminggear-ultracontrol-v2",
    brand: "MeowGamingGear",
    name: "UltraControl V2",
    surface: "control",
    thicknessMm: 3.5,
    dynamicFrictionX: 24,
    dynamicFrictionY: 24,
    staticFrictionX: 26,
    staticFrictionY: 26,
    surfaceTexture: "smooth",
    thickness: 3.5,
    frictionSource: "cisA",
    frictionProxyOf: "MeowGamingGear UltraControl V2 XSoft Orange",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 45,
  },
  {
    slug: "zowie-g-sr-se",
    brand: "Zowie",
    name: "G-SR-SE Roue",
    surface: "control",
    thicknessMm: 3.5,
    dynamicFrictionX: 21,
    dynamicFrictionY: 22,
    staticFrictionX: 23,
    staticFrictionY: 24,
    surfaceTexture: "smooth",
    thickness: 3.5,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 39,
  },
  {
    slug: "razer-gigantus-v2",
    brand: "Razer",
    name: "Gigantus V2",
    surface: "control",
    thicknessMm: 3,
    dynamicFrictionX: 23,
    dynamicFrictionY: 26,
    staticFrictionX: 25,
    staticFrictionY: 28,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Razer Gigantus V2",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 29,
  },
  {
    slug: "lgg-saturn",
    brand: "LGG",
    name: "Saturn",
    surface: "hybrid",
    thicknessMm: 3,
    dynamicFrictionX: 20,
    dynamicFrictionY: 21,
    staticFrictionX: 22,
    staticFrictionY: 24,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 39,
  },
  {
    slug: "artisan-raiden-mid",
    brand: "Artisan",
    name: "Raiden (Mid)",
    surface: "speed",
    thicknessMm: 3,
    dynamicFrictionX: 17.5,
    dynamicFrictionY: 19,
    staticFrictionX: 19,
    staticFrictionY: 21,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Raiden Mid",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 55,
  },
  {
    slug: "ninjutso-npc-control",
    brand: "Ninjutso",
    name: "NPC Control Mousepad",
    surface: "hybrid",
    thicknessMm: 4,
    dynamicFrictionX: 20,
    dynamicFrictionY: 22,
    staticFrictionX: 22,
    staticFrictionY: 25,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 24,
  },
  {
    slug: "logitech-g640-2024",
    brand: "Logitech",
    name: "G640 (2024)",
    surface: "control",
    thicknessMm: 3.2,
    dynamicFrictionX: 19.7,
    dynamicFrictionY: 23.5,
    staticFrictionX: 22,
    staticFrictionY: 27,
    surfaceTexture: "smooth",
    thickness: 3.2,
    frictionSource: "cisA",
    frictionProxyOf: "Logitech G640 2024 (cisA: 19.70/23.50)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 35,
  },
  {
    slug: "razer-strider",
    brand: "Razer",
    name: "Strider",
    surface: "hybrid",
    thicknessMm: 3,
    dynamicFrictionX: 19.7,
    dynamicFrictionY: 21.5,
    staticFrictionX: 21,
    staticFrictionY: 22.5,
    surfaceTexture: "abrasive",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Razer Strider (cisA: 19.70/21.50)",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 39,
  },
  {
    slug: "pulsar-paraspeed",
    brand: "Pulsar",
    name: "ParaSpeed",
    surface: "speed",
    thicknessMm: 3,
    dynamicFrictionX: 15.8,
    dynamicFrictionY: 17.6,
    staticFrictionX: 17,
    staticFrictionY: 19,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Pulsar ParaSpeed (cisA: 15.80/17.60)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 20,
  },
  {
    slug: "artisan-hayate-otsu-soft",
    brand: "Artisan",
    name: "Hayate Otsu (Soft)",
    surface: "hybrid",
    thicknessMm: 4,
    dynamicFrictionX: 20.5,
    dynamicFrictionY: 21,
    staticFrictionX: 22.5,
    staticFrictionY: 23,
    surfaceTexture: "textured",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Hayate Otsu V1 Soft (cisA: 20.50/21.00)",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 65,
  },
  {
    slug: "artisan-hayate-otsu-v2-mid",
    brand: "Artisan",
    name: "Hayate Otsu V2 (Mid)",
    surface: "speed",
    thicknessMm: 3,
    dynamicFrictionX: 19.9,
    dynamicFrictionY: 19.5,
    staticFrictionX: 21,
    staticFrictionY: 20.5,
    surfaceTexture: "textured",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Hayate Otsu V2 Mid",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 65,
  },
  {
    slug: "xraypad-thor",
    brand: "X-raypad",
    name: "Thor",
    surface: "control",
    thicknessMm: 3,
    dynamicFrictionX: 20,
    dynamicFrictionY: 24.5,
    staticFrictionX: 22,
    staticFrictionY: 27,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "X-Raypad Thor (cisA: 20.00/24.50)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 30,
  },
  {
    slug: "pulsar-paracontrol",
    brand: "Pulsar",
    name: "ParaControl",
    surface: "control",
    thicknessMm: 3,
    dynamicFrictionX: 20.5,
    dynamicFrictionY: 23.5,
    staticFrictionX: 24,
    staticFrictionY: 27,
    surfaceTexture: "textured",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Pulsar ParaControl (cisA: 20.50/23.50)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 15,
  },
  {
    slug: "asus-rog-hone-ace",
    brand: "ASUS",
    name: "ROG Hone Ace Aimlab Edition",
    surface: "hybrid",
    thicknessMm: 3.5,
    dynamicFrictionX: 17.3,
    dynamicFrictionY: 20,
    staticFrictionX: 20,
    staticFrictionY: 23,
    surfaceTexture: "textured",
    thickness: 3.5,
    frictionSource: "cisA",
    frictionProxyOf: "ASUS ROG Hone Ace Aimlab Edition (cisA: 17.30/20.00)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 40,
  },
  {
    slug: "artisan-zero-black-xsoft",
    brand: "Artisan",
    name: "Zero (Black, XSoft)",
    surface: "control",
    thicknessMm: 4,
    dynamicFrictionX: 25,
    dynamicFrictionY: 25.3,
    staticFrictionX: 27,
    staticFrictionY: 27.3,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Artisan Zero Black XSoft (cisA: 25.00/25.30)",
    stitchedEdges: false,
    base: "rubber",
    priceUsd: 55,
  },
  {
    slug: "lgg-mercury",
    brand: "Lethal Gaming Gear",
    name: "Mercury",
    surface: "control",
    thicknessMm: 4,
    dynamicFrictionX: 19.5,
    dynamicFrictionY: 23,
    staticFrictionX: 21,
    staticFrictionY: 24.5,
    surfaceTexture: "abrasive",
    thickness: 4,
    frictionSource: "cisA",
    frictionProxyOf: "Lethal Gaming Gear Mercury (cisA: 19.50/23.00)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 30,
  },
  {
    slug: "pulsar-es2",
    brand: "Pulsar",
    name: "ES2",
    surface: "hybrid",
    thicknessMm: 3,
    dynamicFrictionX: 20,
    dynamicFrictionY: 22,
    staticFrictionX: 22,
    staticFrictionY: 24.3,
    surfaceTexture: "smooth",
    thickness: 3,
    frictionSource: "cisA",
    frictionProxyOf: "Pulsar ES2 BLE (cisA: 20.00/22.00)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 40,
  },
  {
    slug: "dark-project-md4-dynamic",
    brand: "Дарк Проджект",
    name: "MD4 Dynamic",
    surface: "speed",
    thicknessMm: 4.3,
    dynamicFrictionX: 17.4,
    dynamicFrictionY: 17.5,
    staticFrictionX: 18.9,
    staticFrictionY: 19,
    surfaceTexture: "smooth",
    thickness: 4.3,
    frictionSource: "cisA",
    frictionProxyOf: "Дарк Проджект MD4 Dynamic (cisA: 17.40/17.50)",
    stitchedEdges: true,
    base: "rubber",
    priceUsd: 45,
  },
  {
    slug: "artisan-key83-soft",
    brand: "Artisan",
    name: "NINJA FX KEY-83 Soft",
    surface: "hybrid",
    thicknessMm: 4,
    dynamicFrictionX: 20,
    dynamicFrictionY: 20,
    staticFrictionX: 22,
    staticFrictionY: 22,
    surfaceTexture: "textured",
    thickness: 4,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "Japanese foam Soft",
    priceUsd: 55,
    releaseYear: 2025,
    sources: [
      {
        label: "Artisan — официальный сайт",
        url: "https://artisan-jp.com/global/fx-key83",
      },
    ],
  },
  {
    slug: "lgg-neptune",
    brand: "Lethal Gaming Gear",
    name: "Neptune",
    surface: "speed",
    thicknessMm: 4,
    dynamicFrictionX: 16,
    dynamicFrictionY: 16,
    staticFrictionX: 18,
    staticFrictionY: 18,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "Japanese rubber foam",
    priceUsd: 35,
    releaseYear: 2025,
    sources: [
      {
        label: "LGG — официальный сайт",
        url: "https://lethal.gg/products/neptune",
      },
    ],
  },
  {
    slug: "lgg-neptune-pro-soft",
    brand: "Lethal Gaming Gear",
    name: "Neptune Pro Soft",
    surface: "speed",
    thicknessMm: 4,
    dynamicFrictionX: 15,
    dynamicFrictionY: 15,
    staticFrictionX: 17,
    staticFrictionY: 17,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "Japanese SlimFlex Soft",
    priceUsd: 55,
    releaseYear: 2025,
    sources: [
      {
        label: "LGG — официальный сайт",
        url: "https://lethal.gg/products/neptune-pro",
      },
    ],
  },
  {
    slug: "pulsar-es-saturn-pro-soft",
    brand: "Pulsar",
    name: "eS Saturn Pro Soft",
    surface: "control",
    thicknessMm: 4,
    dynamicFrictionX: 24,
    dynamicFrictionY: 24,
    staticFrictionX: 26,
    staticFrictionY: 26,
    surfaceTexture: "smooth",
    thickness: 4,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "SlimFlex Soft",
    priceUsd: 50,
    releaseYear: 2026,
    sources: [
      {
        label: "Pulsar eS Pro — официальный каталог",
        url: "https://lethal.gg/collections/pulsar-es-pro-series",
      },
    ],
  },
  {
    slug: "pulsar-es-jupiter-pro-firm",
    brand: "Pulsar",
    name: "eS Jupiter Pro Firm",
    surface: "control",
    thicknessMm: 3,
    dynamicFrictionX: 27,
    dynamicFrictionY: 27,
    staticFrictionX: 29,
    staticFrictionY: 29,
    surfaceTexture: "textured",
    thickness: 3,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "SlimFlex Firm",
    priceUsd: 40,
    releaseYear: 2026,
    sources: [
      {
        label: "Pulsar eS Pro — официальный каталог",
        url: "https://lethal.gg/collections/pulsar-es-pro-series",
      },
    ],
  },
  {
    slug: "pulsar-es-pd170",
    brand: "Pulsar",
    name: "eS PD170",
    surface: "hybrid",
    thicknessMm: 5.5,
    dynamicFrictionX: 21,
    dynamicFrictionY: 21,
    staticFrictionX: 23,
    staticFrictionY: 23,
    surfaceTexture: "smooth",
    thickness: 5.5,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "premium foam",
    priceUsd: 50,
    releaseYear: 2026,
    sources: [
      {
        label: "Pulsar eS Pro — карточка модели",
        url: "https://lethal.gg/products/es-pd170-gaming-mousepad",
      },
    ],
  },
  {
    slug: "wallhack-sp-005",
    brand: "Wallhack",
    name: "SP-005",
    surface: "glass",
    thicknessMm: 3.3,
    dynamicFrictionX: 12,
    dynamicFrictionY: 12,
    staticFrictionX: 14,
    staticFrictionY: 14,
    surfaceTexture: "glass",
    thickness: 3.3,
    frictionSource: "estimated",
    stitchedEdges: false,
    base: "concave silicone",
    priceUsd: 129,
    releaseYear: 2025,
    sources: [
      {
        label: "Wallhack — официальный каталог",
        url: "https://wallhack.com/en-au/collections/glass-mousepads",
      },
    ],
  },
  {
    slug: "wallhack-cr-005",
    brand: "Wallhack",
    name: "CR-005",
    surface: "glass",
    thicknessMm: 3,
    dynamicFrictionX: 17,
    dynamicFrictionY: 17,
    staticFrictionX: 20,
    staticFrictionY: 20,
    surfaceTexture: "glass",
    thickness: 3,
    frictionSource: "estimated",
    stitchedEdges: false,
    base: "concave silicone",
    priceUsd: 129,
    releaseYear: 2025,
    sources: [
      {
        label: "Wallhack — официальный каталог",
        url: "https://wallhack.com/en-uk/collections/mouse-pads",
      },
    ],
  },
  {
    slug: "zowie-g-sr-iii",
    brand: "Zowie",
    name: "G-SR III",
    surface: "control",
    thicknessMm: 3.5,
    dynamicFrictionX: 26,
    dynamicFrictionY: 26,
    staticFrictionX: 28,
    staticFrictionY: 28,
    surfaceTexture: "smooth",
    thickness: 3.5,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "high-density rubber",
    priceUsd: 40,
    releaseYear: 2026,
    sources: [
      {
        label: "Zowie — официальный сайт",
        url: "https://zowie.benq.com/en-au/mouse-pad/g-sr-iii.html",
      },
    ],
  },
  {
    slug: "zowie-h-sr-iii",
    brand: "Zowie",
    name: "H-SR III",
    surface: "control",
    thicknessMm: 3.5,
    dynamicFrictionX: 26,
    dynamicFrictionY: 26,
    staticFrictionX: 28,
    staticFrictionY: 28,
    surfaceTexture: "smooth",
    thickness: 3.5,
    frictionSource: "estimated",
    stitchedEdges: true,
    base: "high-density rubber",
    priceUsd: 50,
    releaseYear: 2026,
    sources: [
      {
        label: "Zowie — официальный сайт",
        url: "https://zowie.benq.com/en-au/mouse-pad/h-sr-iii.html",
      },
    ],
  },
];

export const mice: Mouse[] = [...baseMice, ...extraMice];
export const pads: Mousepad[] = [...basePads, ...extraPads];
